/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VXgE1zV4J0D
 */
import Image from "next/image";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "~/components/ui/accordion";
import { Button } from "~/components/ui/button";
import { Checkbox } from "~/components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";

export function JobListings() {
  return (
    <section key="1" className="w-full py-12 md:py-24 lg:py-32 bg-gray-50">
      <div className="container px-4 md:px-6 mx-auto">
        <div className="grid gap-6 md:gap-8">
          <div className="flex flex-col md:flex-row items-center md:items-center justify-center bg-white rounded-xl shadow-lg h-24 border border-gray-100 overflow-hidden">
            <Input
              className="border-none shadow-none mx-4"
              placeholder="Job title or keyword"
              required
            />
            <div className="hidden md:block border-r border-gray-200 h-full mx-4" />
            <Input
              className="border-none shadow-none mx-4"
              id="location"
              placeholder="City, area or remote"
              required
            />
            <div className="hidden md:block border-r border-gray-200 h-full mx-4" />
            <Select>
              <SelectTrigger className="border-none shadow-none mx-4">
                <SelectValue placeholder="Select a country" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="usa">USA</SelectItem>
                  <SelectItem value="canada">Canada</SelectItem>
                  <SelectItem value="uk">UK</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
            <Button className="bg-gradient-to-bl from-green-700 to-green-900 dark:from-gray-800 dark:to-gray-900 text-white w-full md:w-auto h-full px-16 rounded-none">
              Search
            </Button>
          </div>
          <div className="grid md:grid-cols-[240px_1fr] gap-10 items-start">
            <div className="space-y-4">
              <h2 className="text-xl font-bold tracking-tighter">Filter by</h2>
              <Accordion className="w-full" collapsible type="single">
                <AccordionItem value="roles">
                  <AccordionTrigger className="text-base">
                    Roles
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-marketing-manager" />
                        Marketing Manager
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-content-creator" />
                        Content Creator
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-seo-specialist" />
                        SEO Specialist
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="job-types">
                  <AccordionTrigger className="text-base">
                    Job Types
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-full-time" />
                        Full Time
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-part-time" />
                        Part Time
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-internship" />
                        Internship
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="remote">
                  <AccordionTrigger className="text-base">
                    Remote
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="remote-only" />
                        Remote Only
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </div>
            <div className="grid gap-6 md:gap-8">
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
                <h1 className="text-2xl font-bold tracking-tight">
                  Job Listings (9)
                </h1>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="ml-auto shrink-0" variant="outline">
                      <svg
                        className=" w-4 h-4 mr-2"
                        fill="none"
                        height="24"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        viewBox="0 0 24 24"
                        width="24"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="m21 16-4 4-4-4" />
                        <path d="M17 20V4" />
                        <path d="m3 8 4-4 4 4" />
                        <path d="M7 4v16" />
                      </svg>
                      Sort by
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-[200px]">
                    <DropdownMenuRadioGroup value="featured">
                      <DropdownMenuRadioItem value="featured">
                        Featured
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="newest">
                        Newest
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="low">
                        Salary: Low to High
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="high">
                        Salary: High to Low
                      </DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              {[
                {
                  id: 1,
                  campaignName: "Marketing Campaign Manager",
                  companyName: "Acme Inc.",
                  commissionPerAction: "€0.40 - €0.60 per click",
                },
                {
                  id: 2,
                  campaignName: "Marketing Campaign Specialist",
                  companyName: "Beta Corp.",
                  commissionPerAction: "€0.35 - €0.55 per click",
                },
                {
                  id: 3,
                  campaignName: "Marketing Campaign Coordinator",
                  companyName: "Gamma Ltd.",
                  commissionPerAction: "€0.30 - €0.50 per click",
                },
                {
                  id: 4,
                  campaignName: "Marketing Campaign Analyst",
                  companyName: "Delta Inc.",
                  commissionPerAction: "€0.45 - €0.65 per click",
                },
                {
                  id: 5,
                  campaignName: "Marketing Campaign Director",
                  companyName: "Epsilon Corp.",
                  commissionPerAction: "€0.60 - €0.80 per click",
                },
                {
                  id: 6,
                  campaignName: "Marketing Campaign Assistant",
                  companyName: "Zeta Ltd.",
                  commissionPerAction: "€0.25 - €0.45 per click",
                },
                {
                  id: 7,
                  campaignName: "Marketing Campaign Associate",
                  companyName: "Eta Inc.",
                  commissionPerAction: "€0.40 - €0.60 per click",
                },
                {
                  id: 8,
                  campaignName: "Marketing Campaign Consultant",
                  companyName: "Theta Corp.",
                  commissionPerAction: "€0.50 - €0.70 per click",
                },
                {
                  id: 9,
                  campaignName: "Marketing Campaign Executive",
                  companyName: "Iota Ltd.",
                  commissionPerAction: "€0.55 - €0.75 per click",
                },
              ].map((job, i) => (
                <div
                  className="relative group bg-white p-4 rounded-md grid grid-cols-3 gap-4"
                  key={job.id}
                >
                  <Image
                    alt="Cover image"
                    className="rounded-lg object-cover w-full aspect-w-16 aspect-h-7 group-hover:opacity-50 transition-opacity"
                    height={200}
                    src="/placeholder.svg"
                    width={500}
                  />
                  <div className="flex-1 py-4">
                    <h3 className="font-semibold tracking-tight">
                      {job.campaignName}
                    </h3>
                    <p className="text-zinc-500 dark:text-zinc-400">
                      {job.companyName}
                    </p>
                    <h4 className="font-semibold">{job.commissionPerAction}</h4>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
