/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VXgE1zV4J0D
 */
import Image from "next/image";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "~/components/ui/accordion";
import { Button } from "~/components/ui/button";
import { Checkbox } from "~/components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";

export function JobListings() {
  return (
    <section key="1" className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 md:gap-8">
          <div className="flex flex-col md:flex-row items-center md:items-center justify-center bg-white rounded-md shadow-lg divide-y md:divide-x md:divide-y-0 divide-gray-200 h-24">
            <Input
              className="border-none shadow-none w-min"
              placeholder="Job title or keyword"
              required
            />
            <div className="hidden md:block border-r border-gray-200 h-full mx-4" />
            <Input
              className="border-none shadow-none w-min"
              id="location"
              placeholder="City, area or remote"
              required
            />
            <div className="hidden md:block border-r border-gray-200 h-full mx-4" />
            <Select>
              <SelectTrigger className="border-none shadow-none">
                <SelectValue placeholder="Select a country" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="usa">USA</SelectItem>
                  <SelectItem value="canada">Canada</SelectItem>
                  <SelectItem value="uk">UK</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
            <div className="hidden md:block border-r border-gray-200 h-full mx-4" />
            <Button className="bg-green-600 text-white w-full md:w-auto h-full px-8">
              Search
            </Button>
          </div>
          <div className="grid md:grid-cols-[240px_1fr] gap-10 items-start">
            <div className="space-y-4">
              <h2 className="text-xl font-bold tracking-tighter">Filter by</h2>
              <Accordion className="w-full" collapsible type="single">
                <AccordionItem value="roles">
                  <AccordionTrigger className="text-base">
                    Roles
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-engineer" />
                        Engineer
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-designer" />
                        Designer
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="role-product-manager" />
                        Product Manager
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="job-types">
                  <AccordionTrigger className="text-base">
                    Job Types
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-full-time" />
                        Full Time
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-part-time" />
                        Part Time
                      </Label>
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="type-internship" />
                        Internship
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="remote">
                  <AccordionTrigger className="text-base">
                    Remote
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="grid gap-2">
                      <Label className="flex items-center gap-2 font-normal">
                        <Checkbox id="remote-only" />
                        Remote Only
                      </Label>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </div>
            <div className="grid gap-6 md:gap-8">
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
                <h1 className="text-2xl font-bold tracking-tight">
                  Job Listings (123)
                </h1>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="ml-auto shrink-0" variant="outline">
                      <svg
                        className=" w-4 h-4 mr-2"
                        fill="none"
                        height="24"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        viewBox="0 0 24 24"
                        width="24"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="m21 16-4 4-4-4" />
                        <path d="M17 20V4" />
                        <path d="m3 8 4-4 4 4" />
                        <path d="M7 4v16" />
                      </svg>
                      Sort by
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-[200px]">
                    <DropdownMenuRadioGroup value="featured">
                      <DropdownMenuRadioItem value="featured">
                        Featured
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="newest">
                        Newest
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="low">
                        Salary: Low to High
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="high">
                        Salary: High to Low
                      </DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              <div className="relative group bg-white p-4 rounded-md shadow-sm grid grid-cols-3 gap-4">
                <Image
                  alt="Cover image"
                  className="rounded-lg object-cover w-full aspect-w-16 aspect-h-7 group-hover:opacity-50 transition-opacity"
                  height={200}
                  src="/placeholder.svg"
                  width={500}
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    Senior Product Designer
                  </h3>
                  <p className="text-zinc-500 dark:text-zinc-400">Acme Inc.</p>
                  <h4 className="font-semibold">$80,000 - $90,000</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
