/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sFYqySQcJSM
 */
import Image from "next/image";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";

export function NewsFeed() {
  return (
    <div key="1" className="bg-gray-50 min-h-screen text-white">
      <div className="container mx-auto px-4 py-6 flex gap-4 items-start">
        <div className="sticky top-20 max-w-[300px] w-full rounded-lg bg-white p-4 text-black">
          <Image
            alt="User profile"
            className="rounded-full mb-2"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <h3 className="font-semibold">John Doe</h3>
          <p className="text-sm text-gray-500">
            Instagram Creator & Lifestyle Blogger
          </p>
          <div className="mt-4">
            <h3 className="font-semibold mb-2">Recent Hashtags</h3>
            <p>#gymshark</p>
            <p>#marketing</p>
            <p>#branding</p>
            <p>#fitness</p>
            <p>#apparel</p>
          </div>
        </div>
        <div className="flex-1 flex flex-col gap-4">
          <div className="rounded-lg bg-white p-4 text-black">
            <h2 className="text-xl font-bold">Start a post</h2>
            <div className="mt-2 flex flex-col gap-2">
              <Input
                className="w-full"
                placeholder="Write your post here..."
                type="text"
              />
              <div className="flex flex-row gap-2">
                <Button className="w-full" variant="outline">
                  Upload a photo
                </Button>
                <Button className="w-full" variant="outline">
                  Share a video
                </Button>
              </div>
            </div>
          </div>
          {Array.from({ length: 10 }).map(() => (
            <>
              <div className="rounded-lg bg-white p-4 text-black">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Image
                      alt="User profile"
                      className="rounded-full"
                      height="50"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "50/50",
                        objectFit: "cover",
                      }}
                      width="50"
                    />
                    <div>
                      <h3 className="font-semibold">John Doe</h3>
                      <p className="text-sm text-gray-500">1d ago</p>
                    </div>
                  </div>
                  <svg
                    className=" text-gray-500 h-5 w-5"
                    fill="none"
                    height="24"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    width="24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle cx="12" cy="12" r="1" />
                    <circle cx="19" cy="12" r="1" />
                    <circle cx="5" cy="12" r="1" />
                  </svg>
                </div>
                <p className="mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod eget lorem quis pharetra.
                </p>
                <Image
                  alt="Post image"
                  className="mt-2 rounded"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/200",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="flex items-center justify-between mt-2">
                  <div className="flex items-center gap-2">
                    <Button className="w-1/2 py-0.5 px-2" variant="outline">
                      Like
                    </Button>
                    <Button className="w-1/2 py-0.5 px-2" variant="outline">
                      Share
                    </Button>
                  </div>
                  <p className="text-sm text-gray-500">25 likes</p>
                </div>
                <div className="mt-2">
                  <Input
                    className="w-full"
                    placeholder="New comment..."
                    type="text"
                  />
                </div>
                <div className="mt-2">
                  <p className="font-semibold">Jane Doe</p>
                  <p>This is a comment.</p>
                </div>
                <div className="mt-2">
                  <p className="font-semibold">User 2</p>
                  <p>Another comment on this post.</p>
                </div>
              </div>
            </>
          ))}
        </div>
        <div className="sticky top-20 max-w-[300px] w-full rounded-lg bg-white p-4 text-black">
          <h3 className="font-semibold mb-2">People to follow</h3>
          <div className="grid grid-cols-[50px,1fr] gap-2 pt-2">
            <Image
              alt="User profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h4 className="font-semibold">Jane Doe</h4>
              <p className="text-sm text-gray-500">
                Marketing Manager at Chanel
              </p>
              <Button variant="outline" className="mt-1">
                Follow
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[50px,1fr] gap-2 pt-2">
            <Image
              alt="User profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h4 className="font-semibold">User 2</h4>
              <p className="text-sm text-gray-500">Brand Strategist at Gucci</p>
              <Button variant="outline" className="mt-1">
                Follow
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[50px,1fr] gap-2 pt-2">
            <Image
              alt="User profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h4 className="font-semibold">User 3</h4>
              <p className="text-sm text-gray-500">Product Designer at Prada</p>
              <Button variant="outline" className="mt-1">
                Follow
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[50px,1fr] gap-2 pt-2">
            <Image
              alt="User profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h4 className="font-semibold">User 4</h4>
              <p className="text-sm text-gray-500">
                Fashion Advisor at Louis Vuitton
              </p>
              <Button variant="outline" className="mt-1">
                Follow
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[50px,1fr] gap-2 pt-2">
            <Image
              alt="User profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h4 className="font-semibold">User 5</h4>
              <p className="text-sm text-gray-500">Fashion Analyst at Dior</p>
              <Button variant="outline" className="mt-1">
                Follow
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
